### ISSUE TITLE
Error in deflection for query points

### ISSUE THREAD

**Issue by nicoguaro** [JesseBonanno/IndeterminateBeam#25]
In the example **2(c). Changing units (Readme example)** the deflection shown are:

- 0.004 m for 3 m. But it is closer to 0.0036.
- 0.003 m for 1 m. But it is closer to 0.0026.

**Comment by JesseBonanno** [comment]
Rounding for display purposes, not a mathematical error. Users can change units (using update_units method) if higher precision required.
