### ISSUE TITLE
Decimal Points for kN Units

### ISSUE THREAD

**Issue by berkdemir** [JesseBonanno/IndeterminateBeam#28]
Hi,
Decimal points are default .3f and no option to change. It looks weird when you move to kN & kNm with big beams. An example below. Maybe this option can be squeezed into the update_units() as an option to the user?
![image](https://user-images.githubusercontent.com/40423004/147548569-4ecd9c91-5f00-402f-ac25-c4f13c952bd7.png)

**Comment by JesseBonanno** [comment]
Hi @berkdemir ,

Agreed.

I have made the change as requested with version v2.2.0.

The changes are made in commit 6ce5def.

To change the units in code use the `update_decimal_precision` function. i.e.
`beam.update_decimal_precision(1)`

In the web app there is a new slider in the options that can be used.

Best,
Jesse
