### ISSUE TITLE
Triangular Loads

### ISSUE THREAD

**Issue by Lourenax** [JesseBonanno/IndeterminateBeam#32]
Is there anyway to add a triangular force which its start and end points can be defined along with its start and end magnitudes?

**Comment by JesseBonanno** [comment]
You can use a trapezoidal load with 0 force on one end to create a triangular load.
 https://indeterminatebeam.readthedocs.io/en/main/examples.html#trapezoidal-load

**Comment by Lourenax** [comment]
> You can use a trapezoidal load with 0 force on one end to create a triangular load. https://indeterminatebeam.readthedocs.io/en/main/examples.html#trapezoidal-load

Thanks.
